# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3aaa48982e4617b821bb90fe9d0eb8b707e3d7f343a437ef376de89d84e5f815486b98621df2b17926a5d12f01c08bc7faf2409544289a6fce0eb873af769e0b

  facebook_client_id: '644083385771639'
  facebook_client_secret: '3667bd07786632d3b65f6eb76efc8823'
  github_client_id: '5ad1d86e3ffea093b330'
  github_client_secret: 'a5f7f34ceee7fe1a6985c5f4b636a8503c655df8'
  block_pin: 'foam frequent arrive photo lesson hotel rent gas stool atom issue step'
  block_api: 'd9dc-bbb7-cb86-618d'

test:
  secret_key_base: 818bba82d6b51022edb31d0b0a9455897a94b37720777de00c858d66ecfc2f13bfdec90476a1d1c890ec1feef2d2f2482e9c5238fbdb7903dbc4c6400e9df434

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  facebook_client_id: '644083385771639'
  facebook_client_secret: '3667bd07786632d3b65f6eb76efc8823'
  github_client_id: '5ad1d86e3ffea093b330'
  github_client_secret: 'a5f7f34ceee7fe1a6985c5f4b636a8503c655df8'
  block_pin: 'foam frequent arrive photo lesson hotel rent gas stool atom issue step'
  block_api: 'd9dc-bbb7-cb86-618d'
